hotfix 채팅관련 문제 해결
boostcampwm-2024/iOS08-Shook pull request #291
Opened 2024-12-02 14:14 UTC by INYEKIM

## 💡 요약 및 이슈 

- Resolves: #{이슈번호}

## 📃 작업내용

## 🙋‍♂️ 리뷰노트

## ✅ PR 체크리스트

- [ ] 이 작업으로 인해 변경이 필요한 문서가 변경되었나요? (e.g. `XCConfig`, `노션`, `README`)
- [ ] 이 작업을 하고나서 공유해야할 팀원들에게 공유되었나요? (e.g. `"API 개발 완료됐어요"`, `"XCConfig 값 추가되었어요"`)
- [ ] 작업한 코드가 정상적으로 동작하나요?
- [ ] Merge 대상 브랜치가 올바른가요?
- [ ] PR과 관련 없는 작업이 있지는 않나요?

## 🎸 기타

2024-12-02 14:26 UTC, hyunjuntyler approved these changes
👍👍

2024-12-03 00:59 UTC, Siwon-L requested changes
인예님 같이 디버깅을 조금 해야할 것 같습니다ㅠㅠ

2024-12-03 00:59 UTC, Siwon-L commented on Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChattingListView.swift
> +
인예님, 탭 제스처 영역을 `self`보다는 `chatListView`로 하는 건 어떨까요? 채팅 입력창까지 제스처 영역에 포함되어 있어서, `채팅 보내기` 버튼 클릭 시 간헐적으로 제스처와 버튼 액션이 겹쳐 키보드가 의도하지 않게 내려갑니다.

2024-12-03 00:59 UTC, Siwon-L commented on Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChattingListView.swift
> +                NSLayoutConstraint.activate(self.recentChatButtonHideConstraints)
감사합니닿ㅎㅎ🙏

2024-12-03 00:59 UTC, Siwon-L commented on Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChattingListView.swift
> +    func scrollViewDidEndDecelerating(_ scrollView: UIScrollView) {
인예님 `scrollViewDidEndDecelerating` 호출 시점이 이상합니다ㅠㅠ
버튼이 가장 상단까지 스크롤이 되지 않으면 안올라와요ㅠ

2024-12-03 01:01 UTC, INYEKIM commented on Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChattingListView.swift
> +    func scrollViewDidEndDecelerating(_ scrollView: UIScrollView) {
엇? 한 번 확인해보겠습니다 시원님!

2024-12-03 05:38 UTC, merged