task #48 요청 오류 적용
boostcampwm-2024/iOS08-Shook pull request #49
Opened 2024-11-13 15:04 UTC by hyunjuntyler

## 💡 요약 및 이슈 

### 요청 오류를 정의하고 적용했습니다.

Resolves: #48 

## 📃 작업내용

- `RequestError` 생성
- `RequestError` 적용

## 🙋‍♂️ 리뷰노트

- `RequestError` 네이밍 리뷰 요청드립니다.
- 처음에는 `invalidURL`, `invalidJSONSerialization`으로 했지만 조금더 명확한 오류명이 좋을 것 같아 아래와 같이 네이밍을 지었습니다.

```swift
enum RequestError: Error, LocalizedError {
    case missingURL
    case jsonSerializationFailed(Error)
    
    var errorDescription: String? {
        switch self {
        case .missingURL:
            return "요청에서 유효한 URL을 찾을 수 없습니다."
        case .jsonSerializationFailed(let error):
            return "JSON 직렬화에 실패했습니다: \(error.localizedDescription)"
        }
    }
}
```

## ✅ PR 체크리스트

- [ ] 이 작업으로 인해 변경이 필요한 문서가 변경되었나요? (e.g. `XCConfig`, `노션`, `README`)
- [ ] 이 작업을 하고나서 공유해야할 팀원들에게 공유되었나요? (e.g. `"API 개발 완료됐어요"`, `"XCConfig 값 추가되었어요"`)
- [ ] 작업한 코드가 정상적으로 동작하나요?
- [ ] Merge 대상 브랜치가 올바른가요?
- [ ] PR과 관련 없는 작업이 있지는 않나요?

2024-11-13 15:05 UTC, hyunjuntyler commented on Projects/Modules/NetworkModule/Sources/Request/Encoding/URLQueryEncoder.swift
> +    #warning("배열 query value는 추후 구현")
이부분 살짝 추가로 수정했습니다.

2024-11-13 15:29 UTC, yongbeomkwak requested changes

2024-11-13 15:29 UTC, yongbeomkwak commented on Projects/Modules/NetworkModule/Sources/Request/RequestError.swift
> +        case .jsonSerializationFailed(let error):
직렬화 보다는 encoingfail 같은게 좋지 않을까요 ??

2024-11-14 01:48 UTC, hyunjuntyler commented on Projects/Modules/NetworkModule/Sources/Request/RequestError.swift
> +        case .jsonSerializationFailed(let error):
좋네요! 수정해보겠습니다!

2024-11-14 02:05 UTC, yongbeomkwak approved these changes

2024-11-14 02:14 UTC, merged

2024-11-14 07:04 UTC, INYEKIM commented on Projects/Modules/NetworkModule/Sources/Request/RequestError.swift
> +enum RequestError: Error, LocalizedError {
LocalizedError가 이미 Error를 채택하고 있으니 LocalizedError만 채택하면 어떨까요?! 🥹

2024-11-14 08:58 UTC, hyunjuntyler commented on Projects/Modules/NetworkModule/Sources/Request/RequestError.swift
> +enum RequestError: Error, LocalizedError {
수정했습니다. 감사합니다 👍