task #68 Network에 대한 Default Logger 구현
boostcampwm-2024/iOS08-Shook pull request #70
Opened 2024-11-14 15:26 UTC by yongbeomkwak

## 💡 요약 및 이슈 

### 네트워크 통신 과정의 Requst와 Response를 사용자가 추적하기 쉽게 출력합니다.

Resolves: #68 

## 📃 작업내용

### 프로토콜 정의

다음과 같이 Interceptor 프로토콜을 정의합니다.

```swift
public protocol Interceptor {
    /// request를 보내기 전, 수정할 작업이 있을 경우 ex) token
    func prepare(_ request: URLRequest, from endpoint: Endpoint) throws -> URLRequest
    /// 전달받은 requst
    func willRequest(_ request: URLRequest, from endpoint: Endpoint) throws
    /// response 받았을 때
    func didRecieve(_ result: Response, from endpoint: Endpoint) throws
```

### 대표적인 구현체인 Logger를 구현합니다.

```swift
public final class DefaultLoggingInterceptor: Interceptor { 
....
}
```

### Client 동작 시 알맞은 구간에 Interceptor 동작을 실행합니다.

1. Request

```swift
    func request(_ endpoint: E) async throws -> Response {
        var request = try configureURLRequest(from: endpoint)
        request = try interceptRequest(with: request, from: endpoint)
        return try await requestNetworkTask(with: request, from: endpoint)
    }
```

2. Response

```swift
  func requestNetworkTask(with request: URLRequest, from endpoint: E) async throws -> Response {
        let (data, urlResponse) = try await session.data(for: request)
        let response = Response(request: request, data: data, response: urlResponse)
        try interceptResponse(with: response, from: endpoint)
```

### 테스트 진행

<img width="658" alt="스크린샷 2024-11-15 오전 12 23 03" src="https://github.com/user-attachments/assets/45470e5a-d8cc-4cc4-9067-0eca21df30dd">

<img width="653" alt="스크린샷 2024-11-15 오전 12 23 24" src="https://github.com/user-attachments/assets/2cfc3612-2e80-46d1-a24c-0ca809dfd2b9">

## 🙋‍♂️ 리뷰노트

## ✅ PR 체크리스트

- [ ] 이 작업으로 인해 변경이 필요한 문서가 변경되었나요? (e.g. `XCConfig`, `노션`, `README`)
- [ ] 이 작업을 하고나서 공유해야할 팀원들에게 공유되었나요? (e.g. `"API 개발 완료됐어요"`, `"XCConfig 값 추가되었어요"`)
- [ ] 작업한 코드가 정상적으로 동작하나요?
- [ ] Merge 대상 브랜치가 올바른가요?
- [ ] PR과 관련 없는 작업이 있지는 않나요?

## 🎸 기타

2024-11-14 16:10 UTC, hyunjuntyler requested changes
`Interceptor`를 이렇게 사용하는 거군요...! 많이 배워갑니다... 코드 컨벤션, 오타는 반영해주셨음 합니다!! 나머지는 무시하셔도 돼요

2024-11-14 16:10 UTC, hyunjuntyler commented on Projects/Modules/NetworkModule/Sources/Client/NetworkClient.swift
>      }
이부분 저는 다 없애줬는데 뒤에 머지된 곳에서 `conflict` 해결해야 할 것 같습니다. 아래 보니 테스트도 작성해주셔서 먼저 머지 해주시면 제가 테스트 작성 마무리하는게 좋아보이긴 하네요!

2024-11-14 16:10 UTC, hyunjuntyler commented on Projects/Modules/NetworkModule/Sources/Client/NetworkClient.swift
>      }
아래와 같이 적극적으로 고차함수를 활용해보는것도 좋아보입니다. 물론.. 개인적인... 

```suggestion
    func interceptRequest(with request: URLRequest, from endpoint: E) throws -> URLRequest {
        try interceptors.reduce(request) { currentRequest, interceptor in
            try interceptor.willRequest(currentRequest, from: endpoint)
            return try interceptor.prepare(currentRequest, from: endpoint)
        }
    }
    
    func interceptResponse(with response: Response, from endpoint: E) throws {
        try interceptors.forEach { try $0.didRecieve(response, from: endpoint) }
    }
```

2024-11-14 16:10 UTC, hyunjuntyler commented on Projects/Modules/NetworkModule/Sources/Client/NetworkClient.swift
> +        return requst
오타 수정해주세요!

```suggestion
        return request
```

2024-11-14 16:10 UTC, hyunjuntyler commented on Projects/Modules/NetworkModule/Sources/Interceptor/DefaultLoggingInterceptor.swift
> +    private let logger = Logger(subsystem: Bundle.main.bundleIdentifier ?? "", category: "NETWORK")
이부분 붙여주시면 좋을 것 같습니다! (코드 컨벤션)

```suggestion
public final class DefaultLoggingInterceptor: Interceptor {
    private let logger = Logger(subsystem: Bundle.main.bundleIdentifier ?? "", category: "NETWORK")
```

2024-11-14 16:10 UTC, hyunjuntyler commented on Projects/Modules/NetworkModule/Sources/Interceptor/DefaultLoggingInterceptor.swift
> +}
이부분 붙여주시면 좋을 것 같습니다! (코드 컨벤션) 아래 `extension`은 잘 붙여있는 것 같습니다.

```suggestion
        }
    }
}
```

2024-11-14 16:14 UTC, hyunjuntyler commented on Projects/Modules/NetworkModule/Sources/Interceptor/Interceptor.swift
> +public extension Interceptor { // optinal로 구현하기 위해
이부분은 코드로도 충분히 이해가 가는 부분이라 주석 없어도 될 것 같습니다!

2024-11-15 00:50 UTC, yongbeomkwak commented on Projects/Modules/NetworkModule/Sources/Client/NetworkClient.swift
>      }
넵 그게 좋아보이네요!

2024-11-15 00:51 UTC, yongbeomkwak commented on Projects/Modules/NetworkModule/Sources/Client/NetworkClient.swift
>      }
오 많이 배워갑니다 ! 적용할께요

2024-11-15 00:59 UTC, yongbeomkwak commented
> `Interceptor`를 이렇게 사용하는 거군요...! 많이 배워갑니다...
> 
> 코드 컨벤션, 오타는 반영해주셨음 합니다!! 나머지는 무시하셔도 돼요

> 적용 완료했습니다 확인 부탁드립니다.

2024-11-15 02:38 UTC, hyunjuntyler approved these changes

2024-11-15 03:07 UTC, merged