task #90 #91 방송설정화면 및 방송 중 화면 구현
boostcampwm-2024/iOS08-Shook pull request #98
Opened 2024-11-19 10:08 UTC by INYEKIM

## 💡 요약 및 이슈 

### 방송 설정화면과 방송중인 화면을 구현했습니다.

Resolves: #90 #91

## 📃 작업내용

- 방송세팅 화면
- 방송중인 화면

https://github.com/user-attachments/assets/b3d82c59-86d3-4f9c-88cd-f1c5a5016a64

## 🙋‍♂️ 리뷰노트

방송중인 화면의 ViewModel은 방송 리스트 화면과 같이 사용해서 Dummy로 만들어뒀습니다. 참고부탁드립니다.
채널명 조건은 네이버클라우드에서 직접확인해서 넣어줬습니다!

![스크린샷 2024-11-19 오후 9 44 14](https://github.com/user-attachments/assets/ac184f7d-76ec-416a-9920-070e3abd404f)

## ✅ PR 체크리스트

- [ ] 이 작업으로 인해 변경이 필요한 문서가 변경되었나요? (e.g. `XCConfig`, `노션`, `README`)
- [x] 이 작업을 하고나서 공유해야할 팀원들에게 공유되었나요? (e.g. `"API 개발 완료됐어요"`, `"XCConfig 값 추가되었어요"`)
- [x] 작업한 코드가 정상적으로 동작하나요?
- [x] Merge 대상 브랜치가 올바른가요?
- [ ] PR과 관련 없는 작업이 있지는 않나요?

## 🎸 기타

2024-11-19 14:32 UTC, yongbeomkwak requested changes
errorRed라는 칼러를 못찾았네요
한번 확인해주세요

2024-11-19 14:34 UTC, INYEKIM commented
@yongbeomkwak 아, 이 부분 슬랙으로 공유드렸는데 슬랙 확인해주시면 감사하겠습니다~

> errorRed라는 칼러를 못찾았네요 한 번 확인해주세요

2024-11-19 17:02 UTC, hyunjuntyler reviewed
EasyLayout 부분의 변경사항까지 같이 PR이 올라온것 같은데 확인 부탁드립니다!

2024-11-19 17:02 UTC, hyunjuntyler commented on Projects/Features/BaseFeature/Sources/BaseViewController.swift
> +    public var viewModel: VM
앗 혹시 이부분 Develop 에 포함되어 있는데 머지 받으시면 좋을 것 같습니다!

2024-11-19 17:02 UTC, hyunjuntyler commented on Projects/Features/MainFeature/Sources/BroadcastUIViewController.swift
> +    }
이부분도 `addTarget`으로 할지 `addAction`으로 할지 정하면 좋을 것 같아요

2024-11-19 17:02 UTC, hyunjuntyler commented on Projects/Features/MainFeature/Sources/SettingTableViewCell.swift
> +        errorMessageLabel.textColor = UIColor(red: 255/255, green: 88/255, blue: 65/255, alpha: 1.0)
`alpha: 1` 로 통일하면 좋을 것 같습니다.

2024-11-19 17:02 UTC, hyunjuntyler commented on Projects/Features/MainFeature/Sources/UITableViewCell+Extension.swift
> +}
계산 프로퍼티로 할필요없이 바로 쓸수있지 않나요? 👀

2024-11-19 17:02 UTC, hyunjuntyler commented on Tuist/ProjectDescriptionHelpers/Extensions/Target+Extension.swift
> +            //.userInterface(target: .DesignSystem),
이 주석은 지워주면 좋을 것 같습니다!

2024-11-19 17:14 UTC, Siwon-L approved these changes
고생하셨습니다. 조금 더 task 단위를 나눠도 좋을 것 같아요 예를들어 유효성 검사 같은 경우 별도의 task로 작업해서 issue로 남기면 좋을 것 같습니다

2024-11-19 17:14 UTC, Siwon-L commented on Projects/Features/MainFeature/Sources/UITableViewCell+Extension.swift
> +}
이 친구는 추후에 BaseFeature 쪽으로 이동시키면 좋을 것 같아요.

2024-11-19 17:14 UTC, Siwon-L commented on Tuist/ProjectDescriptionHelpers/Extensions/Target+Extension.swift
> +            //.userInterface(target: .DesignSystem),
그냥 삭제해도 될 것 같아요.

2024-11-19 17:14 UTC, Siwon-L commented on Projects/Features/MainFeature/Sources/SettingUIViewController.swift
> +        // Fonts
주석이 `//`도 있고 `///`도 있는데, 통일시키면 어떨까요? 저희는 `///`을 사용하자고 얘기했던 것 같습니다.

2024-11-20 01:12 UTC, INYEKIM commented on Tuist/ProjectDescriptionHelpers/Extensions/Target+Extension.swift
> +            //.userInterface(target: .DesignSystem),
넵 반영하겠습니다!

2024-11-20 01:13 UTC, INYEKIM commented on Projects/Features/MainFeature/Sources/SettingUIViewController.swift
> +        // Fonts
모든 주석을 Doc comments로 작성하는걸까요?! 이부분은 Doc comments주석이 필요없다고 생각해서 분리만 하는 목적으로 일반 주석으로 작성했습니다 😄

2024-11-20 01:13 UTC, INYEKIM commented on Projects/Features/MainFeature/Sources/UITableViewCell+Extension.swift
> +}
좋은 것 같습니다!!

2024-11-20 01:14 UTC, INYEKIM commented on Projects/Features/BaseFeature/Sources/BaseViewController.swift
> +    public var viewModel: VM
넵! 머지 받았습니다!

2024-11-20 01:14 UTC, INYEKIM commented on Projects/Features/MainFeature/Sources/BroadcastUIViewController.swift
> +    }
좋은 것 같습니다!! 😆

2024-11-20 01:14 UTC, INYEKIM commented on Projects/Features/MainFeature/Sources/SettingTableViewCell.swift
> +        errorMessageLabel.textColor = UIColor(red: 255/255, green: 88/255, blue: 65/255, alpha: 1.0)
넵! 반영했습니다!

2024-11-20 01:14 UTC, INYEKIM commented on Tuist/ProjectDescriptionHelpers/Extensions/Target+Extension.swift
> +            //.userInterface(target: .DesignSystem),
넵! 반영했습니다!

2024-11-20 01:52 UTC, yongbeomkwak approved these changes

2024-11-20 01:52 UTC, hyunjuntyler approved these changes

2024-11-20 01:54 UTC, merged